ens_job:
    path:     /
    defaults: { _controller: "EnsPictonioBundle:Job:index" }

ens_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsPictonioBundle:Job:show" }
    requirements:
        id:   \d+

ens_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsPictonioBundle:Job:preview" }
    requirements:
        token:  \w+

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsPictonioBundle:Job:new" }

ens_job_create:
    path:     /create
    defaults: { _controller: "EnsPictonioBundle:Job:create" }
    methods:  POST

ens_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "EnsPictonioBundle:Job:edit" }
 
ens_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "EnsPictonioBundle:Job:update" }
    requirements: { _method: post }
 
ens_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "EnsPictonioBundle:Job:delete" }
    requirements: { _method: post }

ens_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "EnsPictonioBundle:Job:publish" }
    requirements: { _method: post }

 
ens_job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "EnsPictonioBundle:Job:extend" }
    requirements: { _method: post }